### ISSUE TITLE
about:sitl_study.msg

### ISSUE THREAD

**Issue by Barron-Zh** [shenmuxin/uav_tracking_metaRL#1]
Muxin, hello. 
I encountered the following error while reproducing your code:
from sitl_study.msg import Reward 
ModuleNotFoundError: No module named 'sitl_study'. 
I couldn't find this package. Can you please tell me how to solve it

**Comment by shenmuxin** [comment]
Sry, it's my fault that I changed the ROS pkg name but miss the change in the code, i will fix it. Thank U.

**Comment by shenmuxin** [comment]
Here, you can fix the problem that make sure the ROS pkg name in the `game_avoid.py` is consistent to the `CMakeLists.txt`，as follows:

<div align=center><img src="https://github.com/shenmuxin/uav_tracking_metaRL/assets/87429023/c8d58ba7-03cb-4a85-b214-85d63060d848" alt="Image" width="70%">


<div align=center><img src="https://github.com/shenmuxin/uav_tracking_metaRL/assets/87429023/0602857d-2e4c-4ff9-bcf5-6478eaacc6028" alt="Image" width="70%">

**Comment by shenmuxin** [comment]
These lines just import the custom msgs in this ROS pkg, which are as follows:

<div align=center><img src="https://github.com/shenmuxin/uav_tracking_metaRL/assets/87429023/8d0e9203-598e-4dd4-ac84-45980a619b9f" alt="Image" width="70%">

**Comment by Barron-Zh** [comment]
Thank you for your reply.
